### ISSUE TITLE
modules such as boto3 should be optional for niceman operation

### ISSUE THREAD

**Issue by yarikoptic** [ReproNim/niceman#211]
ATM on a centos (see #207) under conda, after `pip install -e .` fails with
```shell
(niceman-dev) [yhalchen@discovery niceman]$ niceman 
Traceback (most recent call last):
  File "/ihome/yhalchen/.conda/envs/niceman-dev/bin/niceman", line 11, in <module>
    load_entry_point('niceman', 'console_scripts', 'niceman')()
  File "/ihome/yhalchen/proj/repronim/niceman/niceman/cmdline/main.py", line 217, in main
    parser = setup_parser()
  File "/ihome/yhalchen/proj/repronim/niceman/niceman/cmdline/main.py", line 130, in setup_parser
    _mod = import_module(_intfspec[0], package='niceman')
  File "/ihome/yhalchen/.conda/envs/niceman-dev/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/ihome/yhalchen/proj/repronim/niceman/niceman/interface/create.py", line 28, in <module>
    class Create(Interface):
  File "/ihome/yhalchen/proj/repronim/niceman/niceman/interface/create.py", line 92, in Create
    doc=backend_help()
  File "/ihome/yhalchen/proj/repronim/niceman/niceman/interface/base.py", line 258, in backend_help
    ', '.join(ResourceManager._discover_types()))
niceman.support.exceptions.ResourceError: Failed to import resource aws_ec2: No module named boto3 [aws_ec2.py:<module>:12].  Known ones are: aws_ec2, docker_container, session, shell, ssh

```

**Comment by yarikoptic** [comment]
I will submit a quick fix shortly -- I will just ignore those and log at debug level a message

Eventually all of that (detailed help for all backends) shouldn't be done on every run of niceman, including commands which do not care about those options.
