### ISSUE TITLE
NicemanProvenance fails on VCS distributions

### ISSUE THREAD

**Issue by kyleam** [ReproNim/niceman#222]
distributions/base.py makes an incorrect assumption about the module name.

```bash
% cat <<EOF >/tmp/git.yaml
version: 0.0.1
distributions:
- name: git
  packages:
  - path: /home/kyle/src/python/niceman
    branch: bf-recurse-load
    hexsha: 88e5aca75008bd3b5b2bfd18ea7fdef83683bdea
    describe: v0.0.5-142-g88e5aca7
    tracked_remote: .
    remotes:
      chaselgrove:
        url: git@github.com:chaselgrove/niceman.git
      kyleam:
        url: git@github.com:kyleam/niceman.git
      mjtravers:
        url: git@github.com:mjtravers/niceman.git
      origin:
        url: git@github.com:ReproNim/niceman.git
      rbuccigrossi:
        url: git@github.com:rbuccigrossi/ReproNim.git
      yarikoptic:
        contains: true
        url: git@github.com:yarikoptic/ReproNim.git
EOF

% python -c 'from niceman.formats.niceman import NicemanProvenance; NicemanProvenance("/tmp/git.yaml").get_distributions()'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/kyle/src/python/niceman/niceman/formats/niceman.py", line 136, in get_distributions
    spec_class = Distribution.factory(subclass)
  File "/home/kyle/src/python/niceman/niceman/distributions/base.py", line 97, in factory
    module = import_module('niceman.distributions.' + distribution_type.lower())
  File "/home/kyle/src/python/niceman/venv-niceman/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'niceman.distributions.git'
```

This is true on master as well as the rewrite in gh-220.

**Comment by kyleam** [comment]
The core issue is the assumption here:

https://github.com/ReproNim/niceman/blob/67dd17cb7941cb30cb678015410fbe6222e13020/niceman/distributions/base.py#L96-L98

This would fail

  * for `niceman.distributions.vcs.GitDistribution` because the class is in the module "vcs" not "git"

  * for `niceman.distributions.vcs.SVNDistribution` because the class is in the module "vcs" not "svn" and because the class name is `SVNDistribution` not `SvnDistribution`.


To fix this, we could

 1) special case SVN and Git in `Distribution.factory`

 2) restructure things so that the SVN and Git follow the expected naming pattern

 3) maintain a mapping from distribution["name"] -> module.class


@yarikoptic and others, what do you prefer?  (I prefer (3), but I'm quite sure @yarikoptic doesn't.)
