### ISSUE TITLE
Make --trace great again:  wrong error message

### ISSUE THREAD

**Issue by yarikoptic** [ReproNim/niceman#315]
```shell
$> niceman exec --trace /bin/ls
Enter a resource name or ID: localshell
 
2018-10-26 11:37:23,988 [ERROR  ] Using --trace requires ReproZip, a Linux-specific dependency [exec.py:__call__:193] (RuntimeError) 
(dev) 1 14274 ->1.....................................:Fri 26 Oct 2018 11:37:24 AM EDT:.
(git)hopa:~/proj/repronim/niceman[master]git
$> niceman --dbg exec --trace /bin/ls
Enter a resource name or ID: localshell

Traceback (most recent call last):
  File "/home/yoh/proj/repronim/niceman/venvs/dev/bin/niceman", line 11, in <module>
    load_entry_point('niceman', 'console_scripts', 'niceman')()
  File "/home/yoh/proj/repronim/niceman/niceman/cmdline/main.py", line 251, in main
    ret = cmdlineargs.func(cmdlineargs)
  File "/home/yoh/proj/repronim/niceman/niceman/interface/base.py", line 288, in call_from_parser
    return cls.__call__(**kwargs)
  File "/home/yoh/proj/repronim/niceman/niceman/interface/exec.py", line 193, in __call__
    raise RuntimeError("Using --trace requires ReproZip, "
RuntimeError: Using --trace requires ReproZip, a Linux-specific dependency
()
> /home/yoh/proj/repronim/niceman/niceman/interface/exec.py(193)__call__()
-> raise RuntimeError("Using --trace requires ReproZip, "
(Pdb) l
188  	                    local_trace_dir)
189  	
190  	            try:
191  	                from reprozip.tracer.trace import write_configuration
192  	            except ImportError:
193  ->	                raise RuntimeError("Using --trace requires ReproZip, "
194  	                                   "a Linux-specific dependency")
195  	            from rpaths import Path
196  	
197  	            # we rely on hardcoded paths in reprozip
198  	            write_configuration(
(Pdb) from reprozip.tracer.trace import write_configuration
*** ImportError: No module named distro
```

- [x] not sure what about `distro` here. Reprozip is "installed" 
```
(Pdb) import reprozip
(Pdb) print reprozip
<module 'reprozip' from '/home/yoh/proj/repronim/reprozip/reprozip/reprozip/__init__.pyc'>
```
from source git repo
```shell
(git)hopa:~/proj/repronim/reprozip[master]reprozip
$> git describe
1.0.15-107-gbdc6bf71
```

- [ ] error message above is misleading.  Check for `reprozip` presence could/should be done with a dedicated `import reprozip` or better via `external_versions`
```
$> python -c 'from niceman.support.external_versions import external_versions; print(external_versions["reprozip"])'
1.1
$> python -c 'from niceman.support.external_versions import external_versions; print(external_versions["reprozipx"])'
None
```
and then around this import, if fails should report actual exception, instead of the "wrong" error message

**Comment by yarikoptic** [comment]
ok, `distro` is a non issue -- I need to install `distro` (I thought it was about internal submodule import), so renaming the issue to match the only issue of misleading exception message
