### ISSUE TITLE
creating new aws-ec2 instance does not pick up credentials from niceman.cfg

### ISSUE THREAD

**Issue by yarikoptic** [ReproNim/niceman#347]
I have
```shell
$> grep -v '^[# ].*$' ~/.config/niceman/niceman.cfg 
[general]
inventory_file = ~/.config/niceman/inventory.json

[docker]
engine_url = 

[shell]

[aws]
access_key_id = XXXX
secret_access_key = YYYY
```
(XXX and YYY have replaced real values), which used to be picked up to fully setup a configuration for aws-* resource.  But seems to be no longer the case:

```shell
$> niceman --dbg create -t aws-ec2 test-ec2-west -b region_name=us-west-1 image=ami-059e7901352ebaef8 security_group=ssh-only instance_type=t2.medium                                                                                                           Traceback (most recent call last):
  File "/home/yoh/proj/repronim/niceman/venvs/dev3/bin/niceman", line 11, in <module>
    load_entry_point('niceman', 'console_scripts', 'niceman')()
  File "/home/yoh/proj/repronim/niceman/niceman/cmdline/main.py", line 251, in main
    ret = cmdlineargs.func(cmdlineargs)
  File "/home/yoh/proj/repronim/niceman/niceman/interface/base.py", line 288, in call_from_parser
    return cls.__call__(**kwargs)
  File "/home/yoh/proj/repronim/niceman/niceman/interface/create.py", line 137, in __call__
    parse_backend_parameters(backend_parameters))
  File "/home/yoh/proj/repronim/niceman/niceman/resource/base.py", line 310, in create
    resource.connect()
  File "/home/yoh/proj/repronim/niceman/niceman/resource/aws_ec2.py", line 94, in connect
    instances = list(instances)
  File "/usr/lib/python3/dist-packages/boto3/resources/collection.py", line 83, in __iter__
    for page in self.pages():
  File "/usr/lib/python3/dist-packages/boto3/resources/collection.py", line 166, in pages
    for page in pages:
  File "/usr/lib/python3/dist-packages/botocore/paginate.py", line 255, in __iter__
    response = self._make_request(current_kwargs)
  File "/usr/lib/python3/dist-packages/botocore/paginate.py", line 332, in _make_request
    return self._method(**current_kwargs)
  File "/usr/lib/python3/dist-packages/botocore/client.py", line 320, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/lib/python3/dist-packages/botocore/client.py", line 611, in _make_api_call
    operation_model, request_dict)
  File "/usr/lib/python3/dist-packages/botocore/endpoint.py", line 102, in make_request
    return self._send_request(request_dict, operation_model)
  File "/usr/lib/python3/dist-packages/botocore/endpoint.py", line 132, in _send_request
    request = self.create_request(request_dict, operation_model)
  File "/usr/lib/python3/dist-packages/botocore/endpoint.py", line 116, in create_request
    operation_name=operation_model.name)
  File "/usr/lib/python3/dist-packages/botocore/hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/usr/lib/python3/dist-packages/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/usr/lib/python3/dist-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/usr/lib/python3/dist-packages/botocore/signers.py", line 90, in handler
    return self.sign(operation_name, request)
  File "/usr/lib/python3/dist-packages/botocore/signers.py", line 157, in sign
    auth.add_auth(request)
  File "/usr/lib/python3/dist-packages/botocore/auth.py", line 357, in add_auth
    raise NoCredentialsError
botocore.exceptions.NoCredentialsError: Unable to locate credentials

> /usr/lib/python3/dist-packages/botocore/auth.py(357)add_auth()
-> raise NoCredentialsError
(Pdb) 
```
So we lost a way to hide away those sensitive parameters within config while leaving inventory "public" only?

**Comment by yarikoptic** [comment]
actually it seems to not pick them up only on `create` but does pick up (and actually require) on e.g. `install` or `login`.  So seems to be `create` specific

**Comment by kyleam** [comment]
Looks like I broke this in 309bdbbe8 (RF: Absorb more resource handling into ResourceManager, 2018-07-27).  I'll have a closer look.

**Comment by kyleam** [comment]
> Looks like I broke this in [309bdbb](https://github.com/ReproNim/niceman/commit/309bdbbe805bc1f145164dcfd8f44b03f9223bcf) (RF: Absorb more resource handling into ResourceManager, 2018-07-27). I'll have a closer look

Never mind, I was too ready to blame that commit.  I tested its parent and didn't see the credential error, but I failed to actually check that 309bdbb *did* show the error (it doesn't).

**Comment by kyleam** [comment]
> Never mind, I was too ready to blame that commit

Bisects to e99fdbaa1 (CLN: resource: Remove unnecessary code, 2018-09-26).  Will open a PR to revert.
